### ISSUE TITLE
Unit setting in SignalK

### ISSUE THREAD

**Issue by skipperearly** [tkurki/signalk-to-influxdb#38]
Hi Teppo, sorry to bother you here but maybe you can point me in the right direction. Have also raised this question in the openplotter forum. My problem is, that I wish to display the signalK keys xxxxx.temperature and xxx.pressure in C and hPa rather than the standardized units. Have changed the privat unit setting accordingly in the SignalK diagnos options of openplotter but fail to change the unit settings now in InfluxDB/Grafana.   
In the NMEA0183 generation everything works fine, probably as its handled in the plugin rather than in SignalK. 
Is there already a simple solution or could you consider some options within SignalK to apply privat unit setting before data are sent to InfluxDB.
Thanks- and stay healthy! 
Freddie

**Comment by tkurki** [comment]
I convert units to what I want manually in the influx query in Grafana. Just add for example  `* 1. 94384449` for example. Sort of a pain the neck, but dashboards change all the time.

Conversions would need a configuration ui.

As I have mentioned I have a SK native solution for using SK data from influx in Grafana in the works and unit conversion (applied when querying)  is on the backlog. And server side storage for preferred units so that you would not have to configure them everywhere.

**Comment by skipperearly** [comment]
Thanks Teppo, got it to work by adding math -273 in the query.
Keep up the great work and stay healthy!!!!

**Comment by tkurki** [comment]
✅
